artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rahul6796/datasets1/blob/main/conll2003.zip
  local_data_file: artifacts/data_ingestion/ner_dataset.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_FILE_NAME: ["conll2003-train.csv", "conll2003-test.csv", "conll2003-val.csv"]



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/ner_datasetreference.csv
  tokenizer_name: distilbert-base-cased


model_trainer:
  root_dir: artifacts/model_trainer





